### ISSUE TITLE
[DOCS] Add a CONTRIBUTING.md file to the repository

### ISSUE THREAD

**Issue by singodiyashubham87** [Xeeynamo/sotn-decomp#705]
#### Problem or desire

The repository looks incomplete because of the missing CONTRIBUTING.md file to specify the rules and regulations to follow while contributing to the repository, I want to add that file to the repo.

#### Proposal

Add the CONTRIBUTING file to the repository with guidelines.

Kindly assign me this issue.

**Comment by sozud** [comment]
Right now the contributing information is on the wiki

https://github.com/Xeeynamo/sotn-decomp/wiki/Build 
https://github.com/Xeeynamo/sotn-decomp/wiki/Decompilation

I think the wiki makes sense since it doesn't require a PR to edit it. I suppose we could have a CONTRIBUTING.md with links to those pages. @Xeeynamo what do you think?

**Comment by singodiyashubham87** [comment]
@Xeeynamo If you need me to make any changes then do tell me and assign the issue to do a PR.

**Comment by singodiyashubham87** [comment]
@Xeeynamo I will mention the steps to contribute to the repository.

- Fork
- Clone
- Create Branch
- Make Changes
- Stage Changes
- Commit Changes
- Push Changes and create a PR
